[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO